<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" alt="Alternative text" />

A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e análise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

[Guia rápido de uso da biblioteca](https://numpy.org/devdocs/user/quickstart.html)

[Guia para iniciantes](https://numpy.org/devdocs/user/absolute_beginners.html)

___

Qual a diferença entre um numpy array e uma lista?

**numpy array:** armazena somente um tipo de dado (homogêneo), ocupando menos memória. É pensado para maior eficiência de cálculo.

**lista:** permite armazenar dados de vários tipos.

In [1]:
lista = ["a", 2, 2.4, True, [1,3], {"a:1"}]
lista

['a', 2, 2.4, True, [1, 3], {'a:1'}]

In [2]:
lista.append("Olá")
lista

['a', 2, 2.4, True, [1, 3], {'a:1'}, 'Olá']

Importando o numpy

In [3]:
import numpy as np

### Arrays em numpy

<img src = "https://numpy.org/devdocs/_images/np_array.png" />

#### Criando arrays

Pra criar arrays a partir de uma lista, basta utilizar a função **np.array()**

In [4]:
print(np.array([1, 2, 3]))

[1 2 3]


#### Atributos básicos pra um ndarray

In [5]:
_array = np.array([1, 2, 3, 4])

O formato dele

In [6]:
_array.shape

(4,)

Quantas dimensões ele tem

In [7]:
_array.ndim

1

Obter o tipo dos elementos do array (número, letra, ...)

In [8]:
_array.dtype

dtype('int32')

#### Tipo de dados em um ndarray

O dtype de um array do numpy pode ser controlado na hora que a gente cria.

In [9]:
_array = np.array([1, 2, 3, 4], dtype=np.float16)
print(_array)

[1. 2. 3. 4.]


In [10]:
_array.dtype

dtype('float16')

Mas quando a gente não define o tipo de dados?

In [11]:
py_array_2 = [1.0,   2,  3.0]

_array = np.array(py_array_2)

print(_array)
print(_array.dtype)

[1. 2. 3.]
float64


In [12]:
py_array_string = ['a',   2,  3]
np_array_string = np.array(py_array_string)

print(np_array_string)
print(np_array_string.dtype)


['a' '2' '3']
<U11


In [13]:
print(np_array_string.ndim)
print(np_array_string.shape)

1
(3,)


In [14]:
# E se o número for maior que a representação
np.array([1000], dtype=np.int8)

array([-24], dtype=int8)

#### Formas de inicializar Arrays

[numpy zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [15]:
# Array de zeros com np.zeros(n)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# Criando array só com 1s com np.ones(n)
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Tipo Inteiro
np.zeros((5,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

[numpy ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [18]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

[numpy arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange)

In [19]:
# Criando array de números em sequência com o np.arange() - análogo ao range()!
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [20]:
# se der apenas um argumento, o padrão é começar em 0 com passo 1
# ou seja, será uma sequência com o número indicado de elementos, iniciando em zero
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[numpy linspace](https://numpy.org/devdocs/reference/generated/numpy.linspace.html#numpy-linspace)

Gerar um array com **linspace** pode ser bastante útil quando queremos lidar com algumas situações em gráficos.

[numpy random](https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random)

Array com valores aleatorios de uma distribuição uniforme entre 0 e 1 (exclusivo)

Array com inteiros aleatórios dentro de um intervalo

Fixando a seed: números aleatórios reproduzíveis

Também conseguimos trabalhar com **distribuições estatísticas de probabilidade**. Vejamos, por exemplo, como é possível gerar números aleatórios que obedeçam a uma distribuição normal.

<img src = "https://www.allaboutcircuits.com/uploads/articles/an-introduction-to-the-normal-distribution-in-electrical-engineerin-rk-aac-image1.jpg" />

Array com números aleatórios de uma distribuição normal (gaussiana)

__Uma pequena olhada...__

plotando distribuições com o seaborn

#### Indexação

É possível acessar elementos individuais dos arrays pelos **índices**, da mesma forma que fazemos com listas.

<img src = "https://numpy.org/devdocs/_images/np_indexing.png" />

#### Trocando o tipo dos dados nas lista com o .astype()

#### Operações simples

É possível fazer operações matemáticas **elemento a elemento** com os arrays, de forma bem simples:

Em numpy, as operações básicas (+, -, *, /, ...) funcionam elemento a elemento

#### Funções de Agregação

Maior valor

Indice do elemento máximo

Menor valor

Indice do elemento minimo

Soma de todos os items

Media dos elementos

Desvio padrão

Ordenar a lista

#### Filtrando Dados

Uma das funções mais importantes do numpy é a possibilidade de construção de **filtros**, que também são chamados de **máscaras**

O objetivo dos filtros é **selecionar apenas os elementos de um array que satisfaçam determinada condição**

Ao usar um **operador lógico** juntamente com um array, o numpy **aplica a operação lógica a cada um dos elementos do array**, retornando um **array de bools** com o resultado de cada uma das operações lógicas:

Quais elementos do array são menores que um dado valor?

Quantos elementos são maiores que um dado valor?

Uma vez criado o filtro, é possível **utilizá-lo como indexador do array**, para selecionar **apenas os elementos com indice correspondente a True no filtro**

Também é possível aplicar **filtros compostos**!

Pra fazer isso, nós fazems uma **composição lógica** entre os filtros (análogo ao "and" e ao "or")

No caso de arrays, usamos:

- "&" para "and"
- "|" para "or"
- "~" para "not"

[np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

#### Matrizes

Costumamos nos referir às **matrizes** como arrays multidimensionais (i.e., mais de uma dimensão).

<img src = "https://numpy.org/devdocs/_images/np_create_matrix.png"/>

In [21]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

Vamos repetir as operações que aprendemos para descrever um array!

Vamos aprender um função nova para mudar o formato da matriz

[numpy.reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

Em algumas situações, pode ser útil **reformatar** nosso conjunto de dados. Para isso, utilizamos a função *.reshape()*.

**Atenção:** ao utilizar o reshape, o número de elementos total nunca pode ser alterado!

<img src = "https://numpy.org/devdocs/_images/np_reshape.png" />

#### Indexação de matrizes

<img src = "https://numpy.org/devdocs/_images/np_matrix_indexing.png" />

#### Agregações

In [22]:
data = np.array([[1,2],[5,3],[4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])



<img src = "https://numpy.org/devdocs/_images/np_matrix_aggregation.png" />

Também podemos ter situações em que gostaríamos de **agregar por linhas e/ou colunas**, o que também é possível, especificando o parâmetro *axis*, conforme abaixo.

<img src = "https://numpy.org/devdocs/_images/np_matrix_aggregation_row.png" />

"axis = 0" opera na direção das colunas, avaliando entre linhas

"axis = 1" opera na direação das linhas, avaliando entre colunas

#### Operações com matrizes

Operações Elemetares (+, -, *, /)

<img src="https://numpy.org/devdocs/_images/np_matrix_arithmetic.png" />

Diferentemente com arrays unidimensionais, conseguimos operar com matriz de tamanhos diferentes, **desde que sejam essencialmente um vetor-linha ou um vetor-coluna**.

<img src = "https://numpy.org/devdocs/_images/np_matrix_broadcasting.png" />

Multiplicação de Matrizes "tradicional"

[numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

Transposição de Matrizes

Transpor a matriz equivale a "trocar" as linhas pelas colunas.

[numpy.transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

[numpy.ndarray.T](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html)

<img src = "https://numpy.org/devdocs/_images/np_transposing_reshaping.png" />

#### Filtrando Dados

Seguimos a mesma lógica de filtros em arrays unidimensionais, com a particularidade de que estamos lidando, agora, com mais de uma dimensão - e podemos levar isso em consideração.