# Lista de Exercícios de Numpy

Deverá ser entregue até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [1]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
a= np.random.randint(1,101,100)
a

array([ 43,  72,  97,  80,   3,  24,  15,   4,  72,  54,  19,  43,  35,
       100,  54,  98,  14,  64,  55,  78,  47,  83,  34,  32,  24,  83,
        48,  44,  93,  58,  39,  52,  85,   8,  15,  85,  72,  67,  12,
        23,  56,  62,  16,  98,  99,  21,  18,  86,  42,  97,  18,  10,
         7,  98,  63,  42,  70,  64,  10,   8,  62,  64,  87,  56,  86,
        88,  41,  23,  28,   4,   8,  88,  80,   1,  59,  98,  10,   5,
        88,  21,  85,  83,  46,  29,  46,  46,  40, 100,  53,  25,  98,
        44,  41,  90,  14,  15,  86,  12,  34, 100])

In [3]:
a.max()

100

In [4]:
a.min()

1

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [5]:
def modulo(a):
    import numpy as np
    somaquad=0
    for i in a:
        somaquad+=(i*i)
    modulo=(somaquad)**(1/2)
    return (modulo)
    
    

In [6]:
import numpy as np
a = np.array ([1,2,3])

modulo(a)

3.7416573867739413

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)
```

`1.6666666666666665`


In [7]:
# Solução

def calculate_eqm(yp, yi):
    import numpy as np
    soma= (yp-yi)
    somaquad= (soma).dot(soma)
    somatorio= somaquad.sum()
    eqm=(somatorio/(soma.size))
    return(eqm)    

In [8]:
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [9]:
def matriz_miolo_de_pao(a,b):
    arr= np.zeros((a,b))
    arr[0,:]= 1  #primeira linha 
    arr[-1,:]= 1 #última linha  
    arr[:,0]= 1  #primeira coluna
    arr[:,-1]= 1 #última coluna
    return arr

matriz_miolo_de_pao(5,3)
    

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [10]:
def zerou(arr):
    arr[0,:]= 0  #primeira linha 
    arr[-1,:]= 0 #última linha  
    arr[:,0]= 0  #primeira coluna
    arr[:,-1]= 0 #última coluna
    return arr

arr = np.ones((5,3))
zerou(arr)

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [11]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [12]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

NameError: name 'process_EEG_signal' is not defined

In [ ]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

In [ ]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

In [ ]:
# Matriz após o processamento descrito no enunciado
X_processado

In [ ]:
# Solução

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [ ]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

In [ ]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [ ]:
is_outlier

In [ ]:
outliers_count

In [ ]:
outliers

In [ ]:
# Solução

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

## Questão 9

Crie um array de 10 com valores aleatórios

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.