# Lista de Exercícios de Numpy

Deverá ser entregue até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [1]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
a= np.random.randint(1,101,100)
a

array([ 44,  54,   7,  97,  21,  38,  10,  63,  47,  45,  67,  97,  74,
        77,  27,  96, 100,  19, 100,   3,  59,  41,   6,  68,  31,  28,
        26,  33,  94,   8,  45, 100,  57,  47,  47,   5,  52,  10,   2,
        46,  63,  75,  99,  83,  32,  88,  34,  69,  68,  49,  70,  16,
        87,   9,   7,  53,  72,  10,  67,  94,  55,  52,  83,  42,  19,
        47,  50,   5,  49,  20,  80,  77,  40,  23,  99,  33,  10,  23,
        45,  89,  74,   2,  44,  44,  46,  88,  95,  67,  52,  23,  47,
        39,  20,  97,  13,  66,  47,  53,  82,  75])

In [3]:
a.max()

100

In [4]:
a.min()

2

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [5]:
def modulo(a):
    import numpy as np
    somaquad=0
    for i in a:
        somaquad+=(i*i)
    modulo=(somaquad)**(1/2)
    return (modulo)
    
    

In [6]:
import numpy as np
a = np.array ([1,2,3])

modulo(a)

3.7416573867739413

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)
```

`1.6666666666666665`


In [7]:
# Solução

def calculate_eqm(yp, yi):
    import numpy as np
    soma= (yp-yi)
    somaquad= (soma).dot(soma)
    somatorio= somaquad.sum()
    eqm=(somatorio/(soma.size))
    return(eqm)    

In [8]:
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [9]:
def matriz_miolo_de_pao(a,b):
    arr= np.zeros((a,b))
    arr[0,:]= 1  #primeira linha 
    arr[-1,:]= 1 #última linha  
    arr[:,0]= 1  #primeira coluna
    arr[:,-1]= 1 #última coluna
    return arr

matriz_miolo_de_pao(5,3)
    

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [10]:
def zerou(arr):
    arr= np.pad (arr, pad_width=1, mode='constant', constant_values=0)
    return arr

arr = np.ones((5,3))
zerou(arr)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
a =np.array([[2,3,4,5,],
         [5,4,3,2],
         [10,9,8,7],
         [6,5,4,3]])
zerou(a)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  2,  3,  4,  5,  0],
       [ 0,  5,  4,  3,  2,  0],
       [ 0, 10,  9,  8,  7,  0],
       [ 0,  6,  5,  4,  3,  0],
       [ 0,  0,  0,  0,  0,  0]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

```python

# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

```

```
(64, 512)
```

```python
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape
```

```
(64, 512)
```

```python
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()
```
```
-53.08727366483029
```

```python
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X
```
```
array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])
```

```python
# Matriz após o processamento descrito no enunciado
X_processado
```

```
array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])
```

In [12]:
# Solução
def process_EEG_signal (sinal):
    import numpy as np
    media = sinal.mean()
    processado = sinal - media
    return processado

In [13]:
import numpy as np
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [14]:
process_EEG_signal(X)

array([[-0.06726767, -0.0842704 ,  0.88656618, ..., -1.1610474 ,
         0.29329047, -1.29521998],
       [ 1.0588244 ,  1.48982084, -0.37792254, ..., -1.42886741,
         1.66859725, -0.70803605],
       [-0.48435143, -1.50655552,  0.25946845, ..., -0.41959446,
         0.34200259, -0.82458364],
       ...,
       [-0.26537378,  0.06083799, -1.04624597, ...,  0.50339061,
         0.25958002, -0.84868912],
       [-2.00147809, -0.76001986,  1.25251989, ...,  0.02474265,
         0.17716033, -1.24921242],
       [-0.24863326,  1.69168164,  0.32025121, ...,  0.32318777,
        -0.54836062,  0.75487548]])

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de $1,5\cdot IQR - Q1$, ou acima de $1,5\cdot IQR + Q3$.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:
```python
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X
```
Saída:

```
array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])
```

```python
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)
is_outlier
```
Saída:
```
array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])
```

```python
outliers_count
```


`44`


```python
outliers
```
```
array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])
```

In [15]:
# Escreva uma função que, dada uma matriz de dados de entrada de dimensões  𝑁𝑜𝑏𝑠𝑒𝑟𝑣𝑎çõ𝑒𝑠×𝑁𝑓𝑒𝑎𝑡𝑢𝑟𝑒𝑠
# retorne três requisitos:

# - uma matriz booleana indicando a existência de outliers nos dados de entrada;
# - a quantidade de outliers
# - quem são os outliers (os valores).


# Baseei a fómula utilizada nas fórmulas encontradas na seção "Identificando outliers" nesse link: 
# https://escoladedados.org/tutoriais/analise-com-estatistica-descritiva-para-leigos

def locate_outliers(X):
    """
    Recebe: um array do numpy de dimensões  𝑁𝑜𝑏𝑠𝑒𝑟𝑣𝑎çõ𝑒𝑠×𝑁𝑓𝑒𝑎𝑡𝑢𝑟𝑒𝑠.
    Retorna: uma matriz booleana indicando a existência de outliers nos dados de entrada;
    a quantidade de outliers; quem são os outliers (os valores).
    """
    
    import numpy as np
    q1 = np.quantile(X,.25, axis=0) #axis=0 para analisar cada feature, pois as features estão em colunas
    q3 = np.quantile(X,.75, axis=0)
    iqr = (q3 - q1)
    is_outlier = ((X < (q1 - iqr.dot(1.5)))) | (X > (q3 + iqr.dot(1.5)))
    outliers_count = (X[is_outlier]).size
    outliers = X[is_outlier]
    return (is_outlier, outliers_count, outliers)

In [16]:
import numpy as np
X = np.random.randn(300,15)

is_outlier, outliers_count, outliers = locate_outliers(X)
print("Matriz booleana: \n", is_outlier)
print("Contagem de outliers: ", outliers_count)
print("Outliers: \n", outliers)

Matriz booleana: 
 [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
Contagem de outliers:  34
Outliers: 
 [ 3.8303064  -3.02987744 -3.33212329  2.65110752  2.6702679  -3.1598458
 -3.12087613  3.00452494  2.70968992  2.837541   -2.60557899  2.82187813
  2.4622489   3.44682187 -3.14796102  2.53651549  3.32250251  3.4198265
  3.10514477  2.95426145 -3.22252268  2.39617363  3.24080016  2.7590277
 -2.83026587  2.62333999  2.93606719  2.99956006 -2.66633491  2.99630566
  3.13097749  3.21236856  2.78030833  2.24178169]


## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [17]:
jump = np.arange(1, 21, 2)
jump

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Questão 9

Crie um array de 10 com valores aleatórios

In [18]:
aleatorio = np.random.randint(1,10,10)
aleatorio


array([8, 3, 4, 1, 9, 1, 9, 7, 5, 8])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [19]:
def normalize(X):
    """
    Recebe um array do numpy e retorna os valores padronizados em score-z.
    """
    desvio=      X.std()
    media=       X.mean()
    normalizado= (X-media).dot(1/desvio)
    return normalizado

In [20]:
normalize(aleatorio)

array([ 0.84036581, -0.84036581, -0.50421948, -1.51265845,  1.17651213,
       -1.51265845,  1.17651213,  0.50421948, -0.16807316,  0.84036581])

In [21]:
#testando comparando com o z-score do scipy

import scipy.stats as stats
zscores = stats.zscore(aleatorio)
zscores

array([ 0.84036581, -0.84036581, -0.50421948, -1.51265845,  1.17651213,
       -1.51265845,  1.17651213,  0.50421948, -0.16807316,  0.84036581])

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [22]:
def notas (X):
    """
    Recebe: 
    um array do numpy com notas de 100 estudantes.
    
    Retorna um array do Numpy com:
    a média e o desvio-padrão das notas da turma;
    o número de notas maiores que 7.0;
    o número de reprovações da turma;
    a menor nota da turma;
    a maior nota da turma.
    """
    import numpy as np
    
    media = X.mean()
    desvio = X.std()
    count_ma7= (X[X>7]).size
    rep = (X[X<5]).size
    min = X.min()
    max = X.max()
    
    return np.array([media, desvio, count_ma7, rep, min, max])

In [23]:
notas(aleatorio)

array([5.5       , 2.97489496, 4.        , 4.        , 1.        ,
       9.        ])