# Lista de Exercícios de Numpy

Deverá ser entregue até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [1]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
a= np.random.randint(1,101,100)
a

array([ 88,  71,  51,  89,  65,  48,  96,  14,  80,  44,  32,  86,  62,
        35,  35,  64,  49,   8,  61,  16,  89,  20,  44,  97,   4,   6,
        65,  63,  93,  14,  21,  20,  20,  24,  97,  21,  99,  12,  82,
        94,   8,  23,  82,  25,  91,  37,  69,  22,  15,  55,  21,   5,
        80,   4,  67,  20,  63,  60,  49,  54,  51,  94,  31,   5,  96,
        40,  30,   8,  26,  18,  71,  57,  40,   5,  80,   8,  67,  45,
        27,  10,  88,  76,   6,  66,   2,  53,  10,  17,  96,  98,   4,
       100,   1,  26,  39,  46,  59,  44,  53,  22])

In [3]:
a.max()

100

In [4]:
a.min()

1

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [5]:
def modulo(a):
    import numpy as np
    somaquad=0
    for i in a:
        somaquad+=(i*i)
    modulo=(somaquad)**(1/2)
    return (modulo)
    
    

In [6]:
import numpy as np
a = np.array ([1,2,3])

modulo(a)

3.7416573867739413

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)
```

`1.6666666666666665`


In [7]:
# Solução

def calculate_eqm(yp, yi):
    import numpy as np
    soma= (yp-yi)
    somaquad= (soma).dot(soma)
    somatorio= somaquad.sum()
    eqm=(somatorio/(soma.size))
    return(eqm)    

In [8]:
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [9]:
def matriz_miolo_de_pao(a,b):
    arr= np.zeros((a,b))
    arr[0,:]= 1  #primeira linha 
    arr[-1,:]= 1 #última linha  
    arr[:,0]= 1  #primeira coluna
    arr[:,-1]= 1 #última coluna
    return arr

matriz_miolo_de_pao(5,3)
    

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [10]:
def zerou(arr):
    arr[0,:]= 0  #primeira linha 
    arr[-1,:]= 0 #última linha  
    arr[:,0]= 0  #primeira coluna
    arr[:,-1]= 0 #última coluna
    return arr

arr = np.ones((5,3))
zerou(arr)

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

```python

# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

```

```
(64, 512)
```

```python
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape
```

```
(64, 512)
```

```python
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()
```
```
-53.08727366483029
```

```python
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X
```
```
array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])
```

```python
# Matriz após o processamento descrito no enunciado
X_processado
```

```
array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])
```

In [11]:
# Solução
def process_EEG_signal (sinal):
    import numpy as np
    media = sinal.mean()
    sub = media/(sinal.size)
    processado = sinal - sub
    return processado

In [12]:
import numpy as np
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [13]:
process_EEG_signal(X)

array([[ 1.66874978,  0.60241136, -0.56992437, ...,  0.41323477,
        -0.69851053, -1.60479999],
       [-0.15513439, -2.08808195,  0.45905749, ...,  1.75650947,
        -0.94657534,  1.10922003],
       [ 0.99734145, -0.20821234, -0.08079799, ..., -1.45456253,
         0.78073246,  0.27354087],
       ...,
       [ 0.88678138,  0.9361904 , -2.46248787, ...,  0.75313017,
         0.78854796,  1.0307432 ],
       [ 0.16079066,  2.19615664,  0.80543053, ..., -0.193995  ,
        -0.37529087,  2.43734081],
       [ 0.11899973,  0.45736423,  1.84260475, ...,  1.06536358,
         0.44861803, -0.9859185 ]])

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de $1,5\cdot IQR - Q1$, ou acima de $1,5\cdot IQR + Q3$.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:
```python
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X
```
Saída:

```
array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])
```

```python
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)
is_outlier
```
Saída:
```
array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])
```

```python
outliers_count
```


`44`


```python
outliers
```
```
array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])
```

In [14]:
# Escreva uma função que, dada uma matriz de dados de entrada de dimensões  𝑁𝑜𝑏𝑠𝑒𝑟𝑣𝑎çõ𝑒𝑠×𝑁𝑓𝑒𝑎𝑡𝑢𝑟𝑒𝑠
# retorne três requisitos:

# - uma matriz booleana indicando a existência de outliers nos dados de entrada;
# - a quantidade de outliers
# - quem são os outliers (os valores).

def locate_outliers(X):
    """
    Recebe: um array do numpy de dimensões  𝑁𝑜𝑏𝑠𝑒𝑟𝑣𝑎çõ𝑒𝑠×𝑁𝑓𝑒𝑎𝑡𝑢𝑟𝑒𝑠.
    Retorna: uma matriz booleana indicando a existência de outliers nos dados de entrada;
    a quantidade de outliers; quem são os outliers (os valores).
    """
    
    import numpy as np
    q1 = np.quantile(X,.25, axis=0) #axis=0 para analisar cada feature, pois as features estão em colunas
    q3 = np.quantile(X,.75, axis=0)
    iqr = (q3 - q1)
    media = X.mean(axis=0)
    is_outlier = ((X < (media - iqr.dot(1.5)))) | (X > (media + iqr.dot(1.5)))
    outliers_count = (X[is_outlier]).size
    outliers = X[is_outlier]
    return (is_outlier, outliers_count, outliers)

In [15]:
import numpy as np
X = np.random.randn(300,15)

is_outlier, outliers_count, outliers = locate_outliers(X)
print("Matriz booleana: \n", is_outlier)
print("Contagem de outliers: ", outliers_count)
print("Outliers: \n", outliers)

Matriz booleana: 
 [[False False False ... False False False]
 [False  True False ... False False False]
 [False False False ... False False False]
 ...
 [False  True False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
Contagem de outliers:  187
Outliers: 
 [ 1.89622378 -2.70340445  2.23778846  2.38419807  1.96208311  2.77434573
  3.54733899  2.53721431  3.30473368  3.56957114  2.21629824 -1.92851853
  2.19478859  1.88697052 -2.62693522  2.0423175   2.16944143  2.75994742
  2.49550449  2.89315043 -2.3287844  -2.15920887 -1.91730909 -2.4701605
  2.44943213 -2.57599196  1.90821874 -2.37876036 -2.39243589 -3.10155565
  2.67465625  2.01609586  1.97550313 -2.29294224 -2.39000779 -2.04957693
  2.35319816  2.09003213 -3.35611771 -2.53559956 -2.40797823 -2.49741267
  2.1196591  -1.94463953 -2.50018167 -2.37927038 -2.373205   -2.85825687
 -2.33152759  2.16421229  2.02286633 -1.99460548  1.81714183 -3.04796564
 -2.87299054 -2.637650

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [16]:
jump = np.arange(1, 21, 2)
jump

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Questão 9

Crie um array de 10 com valores aleatórios

In [17]:
aleatorio = np.random.randint(1,10,10)
aleatorio


array([7, 6, 1, 3, 9, 7, 2, 3, 9, 9])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [18]:
def normalize(X):
    """
    Recebe um array do numpy e retorna os valores padronizados em score-z.
    """
    desvio=      X.std()
    media=       X.mean()
    normalizado= (X-media).dot(1/desvio)
    return normalizado

In [19]:
normalize(aleatorio)

array([ 0.47628967,  0.13608276, -1.56495178, -0.88453796,  1.15670349,
        0.47628967, -1.22474487, -0.88453796,  1.15670349,  1.15670349])

In [20]:
#testando comparando com o z-score do scipy

import scipy.stats as stats
zscores = stats.zscore(aleatorio)
zscores

array([ 0.47628967,  0.13608276, -1.56495178, -0.88453796,  1.15670349,
        0.47628967, -1.22474487, -0.88453796,  1.15670349,  1.15670349])

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [21]:
def notas (X):
    """
    Recebe: 
    um array do numpy com notas de 100 estudantes.
    
    Retorna:
    a média e o desvio-padrão das notas da turma;
    o número de notas maiores que 7.0;
    o número de reprovações da turma;
    a menor nota da turma;
    a maior nota da turma.
    """
    import numpy as np
    
    media = X.mean()
    desvio = X.std()
    count_ma7= (X[X>7]).size
    rep = (X[X<5]).size
    min = X.min()
    max = X.max()
    
    return np.array([media, desvio, count_ma7, rep, min, max])

In [22]:
notas(aleatorio)

array([5.6       , 2.93938769, 3.        , 4.        , 1.        ,
       9.        ])